use_frameworks!

platform :ios, '9.0'

target 'MyLibrary_Example' do
  pod 'MyLibrary', :path => '../'

  target 'MyLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
